// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registreringstjansten.Data;

#nullable disable

namespace Registreringstjansten.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Registreringstjansten.Models.Registrering", b =>
                {
                    b.Property<int>("RegistreringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistreringId");

                    b.ToTable("Registreringar");
                });

            modelBuilder.Entity("Registreringstjansten.Models.StatusHistorik", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegistreringId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HistoryId");

                    b.HasIndex("RegistreringId");

                    b.ToTable("StatusHistorik");
                });

            modelBuilder.Entity("Registreringstjansten.Models.StatusHistorik", b =>
                {
                    b.HasOne("Registreringstjansten.Models.Registrering", "Registrering")
                        .WithMany("StatusHistorik")
                        .HasForeignKey("RegistreringId");

                    b.Navigation("Registrering");
                });

            modelBuilder.Entity("Registreringstjansten.Models.Registrering", b =>
                {
                    b.Navigation("StatusHistorik");
                });
#pragma warning restore 612, 618
        }
    }
}
