@BookingAPI_HostAddress = https://localhost:7285

###
# ROOMS - GET ALL
GET {{BookingAPI_HostAddress}}/api/rooms
Accept: application/json

###
# ROOMS - GET BY ID
GET {{BookingAPI_HostAddress}}/api/rooms/1
Accept: application/json

###
# ROOMS - CREATE
POST {{BookingAPI_HostAddress}}/api/rooms
Content-Type: application/json

{
  "roomId": 0,
  "roomName": "A101",
  "capacity": 30
}

###
# ROOMS - UPDATE
PUT {{BookingAPI_HostAddress}}/api/rooms/1
Content-Type: application/json

{
  "roomId": 1,
  "roomName": "A102",
  "capacity": 40
}

###
# ROOMS - DELETE
DELETE {{BookingAPI_HostAddress}}/api/rooms/1

###
# ROOMS - GET BOOKINGS FOR ROOM
GET {{BookingAPI_HostAddress}}/api/rooms/1/bookings
Accept: application/json

###
# ROOMS - GET AVAILABLE ROOMS
GET {{BookingAPI_HostAddress}}/api/rooms/available?date=2026-03-20&startTime=10:00:00&endTime=11:00:00
Accept: application/json

###
# ROOM BOOKINGS - GET ALL
GET {{BookingAPI_HostAddress}}/api/roombookings
Accept: application/json

###
# ROOM BOOKINGS - GET BY ID
GET {{BookingAPI_HostAddress}}/api/roombookings/1
Accept: application/json

###
# ROOM BOOKINGS - CREATE (SHOULD WORK)
POST {{BookingAPI_HostAddress}}/api/roombookings
Content-Type: application/json

{
  "bookingId": 0,
  "roomId": 1,
  "date": "2026-03-15T00:00:00",
  "startTime": "09:00:00",
  "endTime": "10:00:00",
  "activityId": 501,
  "bookedByUserId": 10,
  "status": "Created"
}

###
# ROOM BOOKINGS - UPDATE (SHOULD WORK)
PUT {{BookingAPI_HostAddress}}/api/roombookings/4
Content-Type: application/json

{
  "bookingId": 4,
  "roomId": 1,
  "date": "2026-03-14T00:00:00",
  "startTime": "14:00:00",
  "endTime": "15:00:00",
  "activityId": 404,
  "bookedByUserId": 9,
  "status": "UpdatedWithDto"
}

###
# ROOM BOOKINGS - DELETE
DELETE {{BookingAPI_HostAddress}}/api/roombookings/2

###
# ROOM BOOKINGS - CREATE (SHOULD FAIL, TIME CONFLICT)
POST {{BookingAPI_HostAddress}}/api/roombookings
Content-Type: application/json

{
  "bookingId": 0,
  "roomId": 1,
  "date": "2026-03-12T00:00:00",
  "startTime": "10:15:00",
  "endTime": "11:15:00",
  "activityId": 601,
  "bookedByUserId": 11,
  "status": "ConflictTest"
}

###
# ROOM BOOKINGS - UPDATE (SHOULD FAIL, TIME CONFLICT)
PUT {{BookingAPI_HostAddress}}/api/roombookings/1
Content-Type: application/json

{
  "bookingId": 1,
  "roomId": 1,
  "date": "2026-03-12T00:00:00",
  "startTime": "10:00:00",
  "endTime": "11:00:00",
  "activityId": 202,
  "bookedByUserId": 7,
  "status": "ConflictUpdateTest"
}

###
# ROOM BOOKINGS - CREATE (SHOULD FAIL, ROOM DOES NOT EXIST)
POST {{BookingAPI_HostAddress}}/api/roombookings
Content-Type: application/json

{
  "bookingId": 0,
  "roomId": 999,
  "date": "2026-03-16T00:00:00",
  "startTime": "09:00:00",
  "endTime": "10:00:00",
  "activityId": 777,
  "bookedByUserId": 12,
  "status": "WrongRoomTest"
}